#!/bin/bash

# SPDX-FileCopyrightText: 2024 3mdeb <contact@3mdeb.com>
#
# SPDX-License-Identifier: Apache-2.0

SBIN_DIR="/usr/sbin"
BIN_DIR="/usr/bin"
FUM_EFIVAR="/sys/firmware/efi/efivars/FirmwareUpdateMode-d15b327e-ff2d-4fc1-abf6-c12bd08c1359"

export DTS_FUNCS="$SBIN_DIR/dts-functions.sh"
export DTS_ENV="$SBIN_DIR/dts-environment.sh"
export DTS_SUBS="$SBIN_DIR/dts-subscription.sh"
export DTS_HAL="$SBIN_DIR/dts-hal.sh"
export DTS_MOCK_COMMON="$SBIN_DIR/common-mock-func.sh"
export DTS_LOG_FILE="/tmp/dts.log"
export DTS_VERBOSE_LOG_FILE="/tmp/dts-verbose.log"
export BASH_ENV="/$SBIN_DIR/logging"
export SHELLOPTS

# shellcheck source=./logging
source "$BASH_ENV"
start_logging "$DTS_LOG_FILE"
exec {xtrace_fd}>>"${DTS_VERBOSE_LOG_FILE}"
export BASH_XTRACEFD=${xtrace_fd}
set -x

# shellcheck source=../include/dts-environment.sh
source $DTS_ENV
# shellcheck source=../include/dts-functions.sh
source $DTS_FUNCS
# shellcheck source=../include/hal/dts-hal.sh
source $DTS_HAL

if [ -f $FUM_EFIVAR ]; then
    $SBIN_DIR/dasharo-deploy update fum
else
    $SBIN_DIR/dts
fi
