#!/bin/bash

start_logging() {
    local file=$1
    CURRENT_TTY="$(tty)"
    exec 1>> >(tee >(stdbuf -i0 -oL -eL ts "[%T]: " >> "$file")) 2>&1
}

stop_logging() {
    exec &>"$CURRENT_TTY"
}

export PS4="+[\$(date +%T.%3N)]:\${BASH_SOURCE[0]}:\${LINENO[0]}:\${FUNCNAME[0]:-main}: "
export CURRENT_TTY
